name = "Dumb Basses Modpack"
author = "GRocket_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef71348876c2faf353d504a48735200f73277377a000b202c978eb500afe0138"

[versions]
fabric = "0.18.6"
minecraft = "1.20.1"
